schema_version = 0
kind = "core-binaries"
evo_core_tag = "v0.1.10"
target = "x86_64-unknown-linux-gnu"
binaries = ["evo", "evo-plugin-tool"]
built_at = "2026-05-02T17:01:01Z"
publisher = "org.evoframework.core"
