schema_version = 0
kind = "core-binaries"
evo_core_tag = "v0.1.10-rc.2"
target = "x86_64-unknown-linux-gnu"
binaries = ["evo", "evo-plugin-tool"]
built_at = "2026-04-28T12:42:42Z"
publisher = "org.evoframework.core"
