schema_version = 0
kind = "core-binaries"
evo_core_tag = "v0.1.13"
target = "aarch64-unknown-linux-gnu"
binaries = ["evo", "evo-plugin-tool"]
built_at = "2026-09-01T15:34:12Z"
publisher = "org.evoframework.core"

[[auxiliary]]
path = "dist/systemd/evo.service.example"
sha256 = "9a45920ea2c08c3d84ad397d89ef9b5b8aa051f0531d98413cd20058722fd816"

[[auxiliary]]
path = "dist/systemd/README.md"
sha256 = "0c9f3e0bd2c01159d588246ab606ad9e4bb753f1c3721692c57df1fad59988d5"
