schema_version = 0
kind = "core-binaries"
evo_core_tag = "v0.1.10"
target = "armv7-unknown-linux-gnueabihf"
binaries = ["evo", "evo-plugin-tool"]
built_at = "2026-05-02T17:00:33Z"
publisher = "org.evoframework.core"
